mode: 'test'
root_dir: '/media/raffaele/UCM'
device: [0]
experiment: 'multiAP'

model:
  backbone: 'resnet50'
  output_stride: 32
  module: 'none'
  pooling: 'max'
  part_dim: 256
  parts: [[1, 1, 1]]
  num_classes: 17
  pretrained: True
  channels: 3


train:
  nomenclature: 'UCM'
  id_loss:
  metric_loss: 'contrastive_avg'
  loss_weight: [1, 1]
  sim_threshold: 0.5
  mining_strategy: 'ji'
  optimizer: 'adam'
  learning_rate: 1e-4
  epochs: 100
  batch_size: 72
  dataset: 'UCM'
  update_iter: 1
  resume: False
  checkpoint_step: 20


test:
  nomenclature: 'UCM'
  batch_size: 96
  dataset: 'UCM'
  ckpt_directory: '/media/raffaele/UCM/experiments/checkpoints/'
  save: False
  save_path: '/home/rimbriaco/PycharmProjects/DATA/RS/UCM/experiments/outputs/'
  global:
    multi_scale: [1]
  retrieval:
    chunk_size: 250
    seed: 24
    path_gt: '/media/rimbriaco/Seagate Expansion Drive1/RemoteSensing/BigEarthNet/Splits/retrieval_sm2/ji_retrieval_gt.h5'
    visualize: 10
  visualization:
    img_path: '/home/rimbriaco/PycharmProjects/DATA/RS/UCM/Images/'

display:
  summary_step: 100
  display_step: 10

augment_config:
    use_transform: False
    # Image level - probabilities
    h_flip: 0.5
    v_flip: 0.0
    rotate: 0.0

    # Pixel level - probabilities
    blur: 0.1
    brightness: 0.1
    contrast: 0.1
    gamma: 0.1

    # Compose normalize - boolean
    normalize: 1
    compose: 1

    # Image size
    image_size: 256

    # Random Erasing
    random_erasing:
      p: 0.0
      sl: 0.02
      sh: 0.4
      r1: 0.3